version: '3.3'

services:
   database:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myflaskapp
       MYSQL_USER: love
       MYSQL_PASSWORD: 123456

   webapp:
     depends_on:
       - database
     image:  lovesharmadev/webapp
     ports:
       - "8000:80"
     restart: always
  

